# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_author', models.CharField(max_length=20)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
                ('post_creation', models.DateTimeField(default=datetime.datetime(2017, 8, 14, 14, 3, 35, 30686, tzinfo=utc))),
            ],
        ),
    ]
