# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_creation',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 14, 12, 36, 858075, tzinfo=utc)),
        ),
    ]
